
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306"
    networks:
      - movies

  server:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: "mysql"
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/var/www
    depends_on:
      - mysql
    networks:
      - movies

networks:
  movies:
  
volumes:
  db_data:
